use super::types::*;

/// スキルマスターデータを取得
pub fn get_skill(id: &str) -> Option<Skill> {
    match id {
        // パッシブスキル
        // === パッシブスキル ===
        "power_aura" => Some(Skill {
            id: "power_aura".to_string(),
            name: "闘気の波動".to_string(),
            description: "戦闘開始時、味方全員の魔獣数1.15倍".to_string(),
            category: SkillCategory::Passive,
            timing: SkillTiming::BattleStart,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::MonsterCountMultiply,
                target: SkillTarget::AllyUnit,
                value: 1.15,
                duration: None,
            }],
            probability: 100,
        }),
        "wind_blessing" => Some(Skill {
            id: "wind_blessing".to_string(),
            name: "疾風の祝福".to_string(),
            description: "戦闘開始時、味方全員のSPEED+2".to_string(),
            category: SkillCategory::Passive,
            timing: SkillTiming::BattleStart,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::SpeedAdd,
                target: SkillTarget::AllyUnit,
                value: 2.0,
                duration: None,
            }],
            probability: 100,
        }),
        "life_blessing" => Some(Skill {
            id: "life_blessing".to_string(),
            name: "生命の恵み".to_string(),
            description: "戦闘開始時、味方全員の魔獣数+3".to_string(),
            category: SkillCategory::Passive,
            timing: SkillTiming::BattleStart,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::MonsterCountAdd,
                target: SkillTarget::AllyUnit,
                value: 3.0,
                duration: None,
            }],
            probability: 100,
        }),
        "rage_aura" => Some(Skill {
            id: "rage_aura".to_string(),
            name: "猛攻の気迫".to_string(),
            description: "戦闘開始時、ダメージ1.2倍（被ダメも1.15倍）".to_string(),
            category: SkillCategory::Passive,
            timing: SkillTiming::BattleStart,
            effects: vec![
                SkillEffect {
                    effect_type: SkillEffectType::DamageMultiply,
                    target: SkillTarget::AllyUnit,
                    value: 1.2,
                    duration: None,
                },
                SkillEffect {
                    effect_type: SkillEffectType::DamageReduce,
                    target: SkillTarget::AllyUnit,
                    value: -0.15,
                    duration: None,
                },
            ],
            probability: 100,
        }),
        "steel_guard" => Some(Skill {
            id: "steel_guard".to_string(),
            name: "鋼の守り".to_string(),
            description: "戦闘開始時、被ダメージ20%軽減".to_string(),
            category: SkillCategory::Passive,
            timing: SkillTiming::BattleStart,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::DamageReduce,
                target: SkillTarget::SelfOnly,
                value: 0.2,
                duration: None,
            }],
            probability: 100,
        }),
        "iron_fortress" => Some(Skill {
            id: "iron_fortress".to_string(),
            name: "鉄壁の陣".to_string(),
            description: "戦闘開始時、味方全員の被ダメージ10%軽減".to_string(),
            category: SkillCategory::Passive,
            timing: SkillTiming::BattleStart,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::DamageReduce,
                target: SkillTarget::AllyUnit,
                value: 0.1,
                duration: None,
            }],
            probability: 100,
        }),
        "barrier_field" => Some(Skill {
            id: "barrier_field".to_string(),
            name: "結界展開".to_string(),
            description: "戦闘開始時、味方全員にシールド50付与（スキルLvで強化）".to_string(),
            category: SkillCategory::Passive,
            timing: SkillTiming::BattleStart,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Shield,
                target: SkillTarget::AllyUnit,
                value: 50.0,
                duration: None,
            }],
            probability: 100,
        }),
        "thorns" => Some(Skill {
            id: "thorns".to_string(),
            name: "荊の鎧".to_string(),
            description: "戦闘開始時、受けたダメージの20%を反射".to_string(),
            category: SkillCategory::Passive,
            timing: SkillTiming::BattleStart,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::DamageReflect,
                target: SkillTarget::SelfOnly,
                value: 0.2,
                duration: Some(EffectDuration { turns: Some(99), stacks: None, max_stacks: None }),
            }],
            probability: 100,
        }),
        "counter_stance" => Some(Skill {
            id: "counter_stance".to_string(),
            name: "反撃の構え".to_string(),
            description: "戦闘開始時、反撃態勢（50%で反撃）".to_string(),
            category: SkillCategory::Passive,
            timing: SkillTiming::BattleStart,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Counter,
                target: SkillTarget::SelfOnly,
                value: 0.5,
                duration: Some(EffectDuration { turns: Some(99), stacks: None, max_stacks: None }),
            }],
            probability: 100,
        }),
        "shadow_veil" => Some(Skill {
            id: "shadow_veil".to_string(),
            name: "影の帳".to_string(),
            description: "戦闘開始時、回避率+20%".to_string(),
            category: SkillCategory::Passive,
            timing: SkillTiming::BattleStart,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Evasion,
                target: SkillTarget::SelfOnly,
                value: 0.2,
                duration: Some(EffectDuration { turns: Some(99), stacks: None, max_stacks: None }),
            }],
            probability: 100,
        }),
        "mist_cloak" => Some(Skill {
            id: "mist_cloak".to_string(),
            name: "霧隠れ".to_string(),
            description: "戦闘開始時、隠密状態（最初の攻撃を回避）".to_string(),
            category: SkillCategory::Passive,
            timing: SkillTiming::BattleStart,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Stealth,
                target: SkillTarget::SelfOnly,
                value: 1.0,
                duration: Some(EffectDuration { turns: Some(1), stacks: None, max_stacks: None }),
            }],
            probability: 100,
        }),
        "poison_aura" => Some(Skill {
            id: "poison_aura".to_string(),
            name: "瘴気の纏い".to_string(),
            description: "戦闘開始時、敵全員に毒（毎ターン20ダメージ、スキルLvで強化）".to_string(),
            category: SkillCategory::Passive,
            timing: SkillTiming::BattleStart,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Poison,
                target: SkillTarget::EnemyAll,
                value: 20.0,
                duration: Some(EffectDuration { turns: Some(3), stacks: None, max_stacks: None }),
            }],
            probability: 100,
        }),
        "freezing_presence" => Some(Skill {
            id: "freezing_presence".to_string(),
            name: "凍てつく威圧".to_string(),
            description: "戦闘開始時、30%で敵全員を凍結".to_string(),
            category: SkillCategory::Passive,
            timing: SkillTiming::BattleStart,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Freeze,
                target: SkillTarget::EnemyAll,
                value: 1.0,
                duration: Some(EffectDuration { turns: Some(1), stacks: None, max_stacks: None }),
            }],
            probability: 30,
        }),
        "intimidate" => Some(Skill {
            id: "intimidate".to_string(),
            name: "威圧".to_string(),
            description: "戦闘開始時、敵全員のダメージ15%低下".to_string(),
            category: SkillCategory::Passive,
            timing: SkillTiming::BattleStart,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Weaken,
                target: SkillTarget::EnemyAll,
                value: 0.15,
                duration: Some(EffectDuration { turns: Some(2), stacks: None, max_stacks: None }),
            }],
            probability: 100,
        }),
        "last_stand" => Some(Skill {
            id: "last_stand".to_string(),
            name: "背水の陣".to_string(),
            description: "HP50%以下で攻撃力2倍".to_string(),
            category: SkillCategory::Passive,
            timing: SkillTiming::HpLow,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::DamageMultiply,
                target: SkillTarget::SelfOnly,
                value: 2.0,
                duration: None,
            }],
            probability: 100,
        }),
        "first_strike" => Some(Skill {
            id: "first_strike".to_string(),
            name: "先制の心得".to_string(),
            description: "初回攻撃時、ダメージ1.5倍".to_string(),
            category: SkillCategory::Passive,
            timing: SkillTiming::FirstAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::DamageMultiply,
                target: SkillTarget::SelfOnly,
                value: 1.5,
                duration: None,
            }],
            probability: 100,
        }),
        "undying_will" => Some(Skill {
            id: "undying_will".to_string(),
            name: "不屈の意志".to_string(),
            description: "致死ダメージを1回だけHP1で耐える".to_string(),
            category: SkillCategory::Passive,
            timing: SkillTiming::OnDeath,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::MonsterCountSet,
                target: SkillTarget::SelfOnly,
                value: 1.0,
                duration: None,
            }],
            probability: 100,
        }),

        // === アクティブスキル ===
        // ダメージ強化系
        "critical_edge" => Some(Skill {
            id: "critical_edge".to_string(),
            name: "会心撃".to_string(),
            description: "攻撃時、25%でダメージ1.4倍".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::DamageMultiply,
                target: SkillTarget::EnemySingle,
                value: 1.4,
                duration: None,
            }],
            probability: 25,
        }),
        "power_smash" => Some(Skill {
            id: "power_smash".to_string(),
            name: "剛撃".to_string(),
            description: "攻撃時、+80ダメージ（スキルLvで強化）".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::DamageAdd,
                target: SkillTarget::EnemySingle,
                value: 80.0,
                duration: None,
            }],
            probability: 100,
        }),
        "flash_cut" => Some(Skill {
            id: "flash_cut".to_string(),
            name: "閃光斬".to_string(),
            description: "攻撃時、40%でダメージ1.2倍".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::DamageMultiply,
                target: SkillTarget::EnemySingle,
                value: 1.2,
                duration: None,
            }],
            probability: 40,
        }),
        "heavy_impact" => Some(Skill {
            id: "heavy_impact".to_string(),
            name: "重衝撃".to_string(),
            description: "攻撃時、ダメージ1.1倍".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::DamageMultiply,
                target: SkillTarget::EnemySingle,
                value: 1.1,
                duration: None,
            }],
            probability: 100,
        }),
        "sharp_thrust" => Some(Skill {
            id: "sharp_thrust".to_string(),
            name: "鋭突".to_string(),
            description: "攻撃時、+50ダメージ（スキルLvで強化）".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::DamageAdd,
                target: SkillTarget::EnemySingle,
                value: 50.0,
                duration: None,
            }],
            probability: 100,
        }),
        "swift_blade" => Some(Skill {
            id: "swift_blade".to_string(),
            name: "迅刃".to_string(),
            description: "攻撃時、SPEED×0.5を追加ダメージ".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::DamageAdd,
                target: SkillTarget::EnemySingle,
                value: 0.5,
                duration: None,
            }],
            probability: 100,
        }),
        // 複数攻撃・追加攻撃系
        "twin_strike" => Some(Skill {
            id: "twin_strike".to_string(),
            name: "双連撃".to_string(),
            description: "攻撃時、20%で追加攻撃".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::ExtraAttack,
                target: SkillTarget::EnemySingle,
                value: 1.0,
                duration: None,
            }],
            probability: 20,
        }),
        "triple_slash" => Some(Skill {
            id: "triple_slash".to_string(),
            name: "三連斬".to_string(),
            description: "攻撃時、10%で2回追加攻撃".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::ExtraAttack,
                target: SkillTarget::EnemySingle,
                value: 2.0,
                duration: None,
            }],
            probability: 10,
        }),
        "whirlwind" => Some(Skill {
            id: "whirlwind".to_string(),
            name: "旋風撃".to_string(),
            description: "攻撃時、敵全体に40ダメージ+現在HP3%（スキルLvで強化）".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![
                SkillEffect {
                    effect_type: SkillEffectType::TrueDamage,
                    target: SkillTarget::EnemyAll,
                    value: 40.0,
                    duration: None,
                },
                SkillEffect {
                    effect_type: SkillEffectType::PercentDamage,
                    target: SkillTarget::EnemyAll,
                    value: 0.03,
                    duration: None,
                },
            ],
            probability: 100,
        }),
        // 吸収・回復系
        "life_drain" => Some(Skill {
            id: "life_drain".to_string(),
            name: "生命吸収".to_string(),
            description: "攻撃時、与ダメージの25%を回復".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Absorb,
                target: SkillTarget::SelfOnly,
                value: 0.25,
                duration: None,
            }],
            probability: 100,
        }),
        "monster_steal" => Some(Skill {
            id: "monster_steal".to_string(),
            name: "奪命の一撃".to_string(),
            description: "攻撃時、敵から30魔獣数を奪う（スキルLvで強化）".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::MonsterCountSteal,
                target: SkillTarget::EnemySingle,
                value: 30.0,
                duration: None,
            }],
            probability: 100,
        }),
        "heal_strike" => Some(Skill {
            id: "heal_strike".to_string(),
            name: "癒しの剣".to_string(),
            description: "攻撃時、HP最低の味方を30回復（スキルLvで強化）".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Heal,
                target: SkillTarget::AllyLowestHp,
                value: 30.0,
                duration: None,
            }],
            probability: 100,
        }),
        // 防御無視・特殊ダメージ系
        "armor_break" => Some(Skill {
            id: "armor_break".to_string(),
            name: "破甲撃".to_string(),
            description: "攻撃時、敵の防御を無視".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::TrueDamage,
                target: SkillTarget::EnemySingle,
                value: 0.0,
                duration: None,
            }],
            probability: 100,
        }),
        "percent_cut" => Some(Skill {
            id: "percent_cut".to_string(),
            name: "割合斬り".to_string(),
            description: "攻撃時、敵の現在HPの20%ダメージ（スキルLvで強化）".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::PercentDamage,
                target: SkillTarget::EnemySingle,
                value: 0.20,
                duration: None,
            }],
            probability: 100,
        }),
        "execute_blade" => Some(Skill {
            id: "execute_blade".to_string(),
            name: "処刑剣".to_string(),
            description: "攻撃時、敵HP30%以下で即死".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Execute,
                target: SkillTarget::EnemySingle,
                value: 0.3,
                duration: None,
            }],
            probability: 100,
        }),
        // 状態異常付与系
        "blaze_edge" => Some(Skill {
            id: "blaze_edge".to_string(),
            name: "炎刃".to_string(),
            description: "攻撃時、敵に炎上付与（3ターン、毎ターン30ダメージ、スキルLvで強化）".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Burn,
                target: SkillTarget::EnemySingle,
                value: 30.0,
                duration: Some(EffectDuration { turns: Some(3), stacks: None, max_stacks: None }),
            }],
            probability: 100,
        }),
        "venom_fang" => Some(Skill {
            id: "venom_fang".to_string(),
            name: "毒牙".to_string(),
            description: "攻撃時、敵に毒付与（3ターン、毎ターン20ダメージ、スキルLvで強化）".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Poison,
                target: SkillTarget::EnemySingle,
                value: 20.0,
                duration: Some(EffectDuration { turns: Some(3), stacks: None, max_stacks: None }),
            }],
            probability: 100,
        }),
        "frost_blade" => Some(Skill {
            id: "frost_blade".to_string(),
            name: "氷刃".to_string(),
            description: "攻撃時、25%で敵を凍結（1ターン行動不能）".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Freeze,
                target: SkillTarget::EnemySingle,
                value: 1.0,
                duration: Some(EffectDuration { turns: Some(1), stacks: None, max_stacks: None }),
            }],
            probability: 25,
        }),
        "thunder_strike" => Some(Skill {
            id: "thunder_strike".to_string(),
            name: "雷撃".to_string(),
            description: "攻撃時、30%で敵を気絶（1ターン行動不能）".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Stun,
                target: SkillTarget::EnemySingle,
                value: 1.0,
                duration: Some(EffectDuration { turns: Some(1), stacks: None, max_stacks: None }),
            }],
            probability: 30,
        }),
        "curse_touch" => Some(Skill {
            id: "curse_touch".to_string(),
            name: "呪縛の手".to_string(),
            description: "攻撃時、敵を脆弱化（被ダメージ20%増加、2ターン）".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Vulnerable,
                target: SkillTarget::EnemySingle,
                value: 0.2,
                duration: Some(EffectDuration { turns: Some(2), stacks: None, max_stacks: None }),
            }],
            probability: 100,
        }),
        "silence_cut" => Some(Skill {
            id: "silence_cut".to_string(),
            name: "封魔斬".to_string(),
            description: "攻撃時、40%で敵を沈黙（スキル使用不可、2ターン）".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Silence,
                target: SkillTarget::EnemySingle,
                value: 1.0,
                duration: Some(EffectDuration { turns: Some(2), stacks: None, max_stacks: None }),
            }],
            probability: 40,
        }),
        // バフ付与系
        "battle_cry" => Some(Skill {
            id: "battle_cry".to_string(),
            name: "鼓舞".to_string(),
            description: "攻撃時、味方全員の攻撃力+10%（2ターン）".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::AttackBuff,
                target: SkillTarget::AllyUnit,
                value: 0.1,
                duration: Some(EffectDuration { turns: Some(2), stacks: None, max_stacks: None }),
            }],
            probability: 100,
        }),
        "shield_bash" => Some(Skill {
            id: "shield_bash".to_string(),
            name: "盾撃".to_string(),
            description: "攻撃時、自分にシールド30付与（スキルLvで強化）".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Shield,
                target: SkillTarget::SelfOnly,
                value: 30.0,
                duration: None,
            }],
            probability: 100,
        }),
        // デバフ解除・バフ解除系
        "purify_strike" => Some(Skill {
            id: "purify_strike".to_string(),
            name: "浄化の一撃".to_string(),
            description: "攻撃時、自分のデバフを1つ解除".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Cleanse,
                target: SkillTarget::SelfOnly,
                value: 1.0,
                duration: None,
            }],
            probability: 100,
        }),
        "dispel_blow" => Some(Skill {
            id: "dispel_blow".to_string(),
            name: "破魔撃".to_string(),
            description: "攻撃時、敵のバフを1つ解除".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Dispel,
                target: SkillTarget::EnemySingle,
                value: 1.0,
                duration: None,
            }],
            probability: 100,
        }),
        // 特殊系
        "mark_target" => Some(Skill {
            id: "mark_target".to_string(),
            name: "狙撃".to_string(),
            description: "攻撃時、敵にマーク付与（被ダメージ+50、3ターン、スキルLvで強化）".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Mark,
                target: SkillTarget::EnemySingle,
                value: 50.0,
                duration: Some(EffectDuration { turns: Some(3), stacks: None, max_stacks: None }),
            }],
            probability: 100,
        }),
        "taunt_blow" => Some(Skill {
            id: "taunt_blow".to_string(),
            name: "挑発撃".to_string(),
            description: "攻撃時、自分に挑発付与（敵の攻撃を引きつける）".to_string(),
            category: SkillCategory::Active,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Taunt,
                target: SkillTarget::SelfOnly,
                value: 1.0,
                duration: Some(EffectDuration { turns: Some(2), stacks: None, max_stacks: None }),
            }],
            probability: 100,
        }),

        // === ユニークスキル ===
        // 攻撃強化系
        "divine_spear" => Some(Skill {
            id: "divine_spear".to_string(),
            name: "神槍・絶命".to_string(),
            description: "攻撃時、ダメージ1.6倍".to_string(),
            category: SkillCategory::Unique,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::DamageMultiply,
                target: SkillTarget::EnemySingle,
                value: 1.6,
                duration: None,
            }],
            probability: 100,
        }),
        "thunder_call" => Some(Skill {
            id: "thunder_call".to_string(),
            name: "雷神招来".to_string(),
            description: "攻撃時、50%で敵全体に+100ダメージ（スキルLvで強化）".to_string(),
            category: SkillCategory::Unique,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::TrueDamage,
                target: SkillTarget::EnemyAll,
                value: 100.0,
                duration: None,
            }],
            probability: 50,
        }),
        // 蘇生・不死系
        "fake_death" => Some(Skill {
            id: "fake_death".to_string(),
            name: "偽りの死".to_string(),
            description: "死亡時、50%で魔獣数半分で復活".to_string(),
            category: SkillCategory::Unique,
            timing: SkillTiming::OnDeath,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Revive,
                target: SkillTarget::SelfOnly,
                value: 0.5,
                duration: None,
            }],
            probability: 50,
        }),
        "phoenix_rebirth" => Some(Skill {
            id: "phoenix_rebirth".to_string(),
            name: "不死鳥の転生".to_string(),
            description: "死亡時、100%で魔獣数全快で復活（1回のみ）".to_string(),
            category: SkillCategory::Unique,
            timing: SkillTiming::OnDeath,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Revive,
                target: SkillTarget::SelfOnly,
                value: 1.0,
                duration: None,
            }],
            probability: 100,
        }),
        // バフ系
        "beauty_charm" => Some(Skill {
            id: "beauty_charm".to_string(),
            name: "美神の輝き".to_string(),
            description: "戦闘開始時、味方全員の魔獣数1.5倍".to_string(),
            category: SkillCategory::Unique,
            timing: SkillTiming::BattleStart,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::MonsterCountMultiply,
                target: SkillTarget::AllyUnit,
                value: 1.5,
                duration: None,
            }],
            probability: 100,
        }),
        "war_god_blessing" => Some(Skill {
            id: "war_god_blessing".to_string(),
            name: "軍神の加護".to_string(),
            description: "戦闘開始時、味方全員に無敵（1回攻撃無効）".to_string(),
            category: SkillCategory::Unique,
            timing: SkillTiming::BattleStart,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Invincible,
                target: SkillTarget::AllyUnit,
                value: 1.0,
                duration: None,
            }],
            probability: 100,
        }),
        // 即死・処刑系
        "death_sentence" => Some(Skill {
            id: "death_sentence".to_string(),
            name: "死刑宣告".to_string(),
            description: "攻撃時、敵HP50%以下で即死".to_string(),
            category: SkillCategory::Unique,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Execute,
                target: SkillTarget::EnemySingle,
                value: 0.5,
                duration: None,
            }],
            probability: 100,
        }),
        "soul_reap" => Some(Skill {
            id: "soul_reap".to_string(),
            name: "魂狩り".to_string(),
            description: "敵を倒した時、その敵の魔獣数の50%を獲得".to_string(),
            category: SkillCategory::Unique,
            timing: SkillTiming::OnKill,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::MonsterCountSteal,
                target: SkillTarget::EnemySingle,
                value: 0.5,
                duration: None,
            }],
            probability: 100,
        }),
        // 状態異常系
        "absolute_zero" => Some(Skill {
            id: "absolute_zero".to_string(),
            name: "絶対零度".to_string(),
            description: "戦闘開始時、敵全員を凍結（1ターン行動不能）".to_string(),
            category: SkillCategory::Unique,
            timing: SkillTiming::BattleStart,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Freeze,
                target: SkillTarget::EnemyAll,
                value: 1.0,
                duration: Some(EffectDuration { turns: Some(1), stacks: None, max_stacks: None }),
            }],
            probability: 100,
        }),
        "plague_touch" => Some(Skill {
            id: "plague_touch".to_string(),
            name: "疫病の手".to_string(),
            description: "攻撃時、敵全員に毒付与（毎ターン50ダメージ、3ターン、スキルLvで強化）".to_string(),
            category: SkillCategory::Unique,
            timing: SkillTiming::OnAttack,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::Poison,
                target: SkillTarget::EnemyAll,
                value: 50.0,
                duration: Some(EffectDuration { turns: Some(3), stacks: None, max_stacks: None }),
            }],
            probability: 100,
        }),
        // 特殊系
        "time_stop" => Some(Skill {
            id: "time_stop".to_string(),
            name: "時間停止".to_string(),
            description: "戦闘開始時、味方全員が2回行動".to_string(),
            category: SkillCategory::Unique,
            timing: SkillTiming::BattleStart,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::ExtraAttack,
                target: SkillTarget::AllyUnit,
                value: 1.0,
                duration: None,
            }],
            probability: 100,
        }),
        "mirror_force" => Some(Skill {
            id: "mirror_force".to_string(),
            name: "鏡像反転".to_string(),
            description: "戦闘開始時、受けたダメージを100%反射（1回）".to_string(),
            category: SkillCategory::Unique,
            timing: SkillTiming::BattleStart,
            effects: vec![SkillEffect {
                effect_type: SkillEffectType::DamageReflect,
                target: SkillTarget::SelfOnly,
                value: 1.0,
                duration: Some(EffectDuration { turns: Some(1), stacks: None, max_stacks: None }),
            }],
            probability: 100,
        }),
        "dimensional_rift" => Some(Skill {
            id: "dimensional_rift".to_string(),
            name: "次元断裂".to_string(),
            description: "攻撃時、敵のバフを全て解除し、自分にコピー".to_string(),
            category: SkillCategory::Unique,
            timing: SkillTiming::OnAttack,
            effects: vec![
                SkillEffect {
                    effect_type: SkillEffectType::Dispel,
                    target: SkillTarget::EnemySingle,
                    value: 99.0,
                    duration: None,
                },
                SkillEffect {
                    effect_type: SkillEffectType::CopyBuff,
                    target: SkillTarget::SelfOnly,
                    value: 1.0,
                    duration: None,
                },
            ],
            probability: 100,
        }),
        "sacrifice" => Some(Skill {
            id: "sacrifice".to_string(),
            name: "生贄の儀".to_string(),
            description: "自分のHP半分を消費し、味方全員の魔獣数2倍".to_string(),
            category: SkillCategory::Unique,
            timing: SkillTiming::BattleStart,
            effects: vec![
                SkillEffect {
                    effect_type: SkillEffectType::PercentDamage,
                    target: SkillTarget::SelfOnly,
                    value: 0.5,
                    duration: None,
                },
                SkillEffect {
                    effect_type: SkillEffectType::MonsterCountMultiply,
                    target: SkillTarget::AllyUnit,
                    value: 2.0,
                    duration: None,
                },
            ],
            probability: 100,
        }),

        _ => None,
    }
}
